-- Top 10 customers by total spending
SELECT c.customer_id, SUM(p.payment_value) AS total_spending
FROM customers AS c
INNER JOIN orders AS o
ON c.customer_id = o.customer_id
INNER JOIN order_payments AS p
ON p.order_id = o.order_id
GROUP BY c.customer_id
ORDER BY total_spending DESC
LIMIT 10;

-- Top 10 States by Total Revenue
SELECT c.customer_state, SUM(oi.price) AS total_revenue
FROM customers AS c
INNER JOIN orders AS o
ON c.customer_id = o.customer_id
INNER JOIN order_items AS oi
ON o.order_id = oi.order_id
GROUP BY c.customer_state
ORDER BY total_revenue DESC
LIMIT 10;

-- Top 10 Product Categories by Revenue
SELECT p.product_category_name, SUM(oi.price) AS total_revenue
FROM products AS p
INNER JOIN order_items AS oi
ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY total_revenue DESC
LIMIT 10;

-- Top 10 Sellers by Number of Orders
SELECT s.seller_id, COUNT(DISTINCT oi.order_id) AS total_orders
FROM sellers AS s
INNER JOIN order_items AS oi
ON s.seller_id = oi.seller_id
GROUP BY s.seller_id
ORDER BY total_orders DESC
LIMIT 10;

-- Revenue by Payment Type
SELECT op.payment_type, SUM(oi.price) AS total_revenue
FROM order_payments AS op
INNER JOIN order_items AS oi
ON op.order_id = oi.order_id
GROUP BY op.payment_type
ORDER BY total_revenue DESC;

-- Top 10 Customers by Number of Orders
SELECT 	c.customer_id, COUNT(o.order_id) AS total_orders
FROM Customers AS c
INNER JOIN orders AS o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id
ORDER BY total_orders DESC
LIMIT 10;

-- Customers who placed more than 5 orders
SELECT c.customer_id, COUNT(o.order_id) AS total_orders
FROM Customers AS c
INNER JOIN orders AS o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id
HAVING COUNT(o.order_id) > 5;

-- Average Order Value
SELECT AVG(payment_value) AS average_order_value
FROM order_payments;

-- Delivered vs Cancelled Orders
SELECT order_status, COUNT(order_id) AS total_orders
FROM orders
WHERE order_status IN ('delivered', 'cancelled')
GROUP BY order_status;

-- Top 10 Cities by Revenue
SELECT c.customer_city, SUM(oi.price) AS total_revenue
FROM customers AS c
INNER JOIN orders AS o
ON c.customer_id = o.customer_id
INNER JOIN order_items AS oi
ON o.order_id = oi.order_id
GROUP BY c.customer_city
ORDER BY total_revenue DESC
LIMIT 10;

-- Top 10 Sellers by Revenue
SELECT seller_id, SUM(price) AS total_revenue
FROM order_items
GROUP BY seller_id
ORDER BY total_revenue DESC
LIMIT 10;

-- Average Revenue per Seller
SELECT seller_id, AVG(price) AS average_revenue
FROM order_items
GROUP BY seller_id
ORDER BY average_revenue DESC;

-- Top 10 Product Categories by Number of Products Sold
SELECT p.product_category_name, COUNT(oi.product_id) AS total_products_sold
FROM products AS p
INNER JOIN order_items AS oi
ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY total_products_sold DESC
LIMIT 10;

-- Customers who spent more than the average payment
SELECT customer_id, payment_value
FROM orders AS o
INNER JOIN order_payments AS op
ON o.order_id = op.order_id
WHERE payment_value >
(
    SELECT AVG(payment_value)
    FROM order_payments
);

-- Revenue Generated by Each Seller State
SELECT s.seller_state, SUM(oi.price) AS total_revenue
FROM sellers AS s
INNER JOIN order_items AS oi
ON s.seller_id = oi.seller_id
GROUP BY s.seller_state
ORDER BY total_revenue DESC;

-- Top 10 Cities by Number of Customers
SELECT customer_city, COUNT(customer_id) AS total_customers
FROM customers
GROUP BY customer_city
ORDER BY total_customers DESC
LIMIT 10;

-- Average Freight Cost by Seller
SELECT seller_id, AVG(freight_value) AS average_freight_cost
FROM order_items
GROUP BY seller_id
ORDER BY average_freight_cost DESC;